#!/usr/bin/env python3
"""家庭网络规则管线的生成器。

编译可信上游与本地manifest为mosdns域名表与Surge RULE-SET文件，写入本仓库的
generated/目录；产物有变化时提交并推送到GitHub，随后请求jsdelivr刷新对应文件。
不SSH到任何NAS，也不写任何iCloud路径——两台NAS各自的拉取与Surge侧的静态
RULE-SET引用是本仓库之外的消费方，不由本脚本触达。
"""
import argparse
import datetime as dt
import hashlib
import json
import logging
from logging.handlers import RotatingFileHandler
import os
from pathlib import Path
import re
import shlex
import subprocess
import sys
import tempfile
import urllib.request


class RuleError(RuntimeError):
    pass


DOMAIN_LABEL = re.compile(r"^[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?$")


def utc_now():
    return dt.datetime.now(dt.timezone.utc).replace(microsecond=0).isoformat()


def sha256_bytes(data):
    return hashlib.sha256(data).hexdigest()


def normalize_domain(value, allow_single=False):
    domain = value.strip().strip("'\"").lower().rstrip(".")
    if domain.startswith("+."):
        domain = domain[2:]
    elif domain.startswith("."):
        domain = domain[1:]
    if any(token in domain for token in ("/", ":", ",", "*", " ", "\t")):
        raise RuleError("unsupported domain expression: %s" % value)
    try:
        domain = domain.encode("idna").decode("ascii")
    except UnicodeError as exc:
        raise RuleError("invalid IDN: %s" % value) from exc
    labels = domain.split(".")
    if any(not DOMAIN_LABEL.fullmatch(label) for label in labels):
        raise RuleError("invalid domain: %s" % value)
    return domain


def parse_clash_payload(text, source_name):
    entries = set()
    for line_number, raw in enumerate(text.splitlines(), 1):
        line = raw.strip()
        if not line or line.startswith("#") or line == "payload:":
            continue
        match = re.fullmatch(r"-\s*['\"]?([^'\"]+)['\"]?", line)
        if not match:
            raise RuleError("%s:%d unsupported line: %s" % (source_name, line_number, line[:160]))
        value = match.group(1).strip()
        if value.startswith("+."):
            kind, value = "domain", value[2:]
        elif value.startswith("domain:"):
            kind, value = "domain", value[len("domain:"):]
        elif value.startswith("full:"):
            kind, value = "full", value[len("full:"):]
        else:
            kind = "full"
        entries.add("%s:%s" % (kind, normalize_domain(value, allow_single=(kind == "full"))))
    return entries


def read_rule_entries(path):
    if not path.exists():
        return set()
    entries = set()
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        if ":" not in line:
            line = "domain:" + normalize_domain(line)
        else:
            kind, value = line.split(":", 1)
            if kind in ("domain", "full"):
                line = "%s:%s" % (kind, normalize_domain(value, allow_single=(kind == "full")))
            elif kind == "regexp":
                if not value:
                    raise RuleError("empty regexp in %s" % path)
            else:
                raise RuleError("unsupported rule in %s: %s" % (path, line))
        entries.add(line)
    return entries


def render_entries(entries):
    return "".join(entry + "\n" for entry in sorted(entries)).encode("utf-8")


def entry_domain(entry):
    return entry.split(":", 1)[1]


def without_domains(entries, excluded):
    return {entry for entry in entries if entry_domain(entry) not in excluded}


def forced_suffixes(manifest):
    """manifest.forced_proxy.domains：这些后缀（含其全部子域）一律交给代理支，并从所有直连产物剔除。"""
    return sorted({normalize_domain(item) for item in manifest.get("forced_proxy", {}).get("domains", [])})


def under_suffix(domain, suffixes):
    return any(domain == suffix or domain.endswith("." + suffix) for suffix in suffixes)


def without_forced(entries, suffixes):
    return {entry for entry in entries if not under_suffix(entry_domain(entry), suffixes)}


def render_surge_proxy_ruleset(suffixes):
    """渲染Surge消费的强制代理规则集：每行DOMAIN-SUFFIX,<域名>，不带策略；消费方必须把它排在直连规则集之前。"""
    lines = [
        "# Generated by home-network-rules/update_rules.py. Edit manifest.json (forced_proxy), not this file.",
        "# Consume as: RULE-SET,<jsdelivr URL to this file>,Proxy,update-interval=43200 -- place it BEFORE the direct ruleset line",
    ]
    lines.extend("DOMAIN-SUFFIX,%s" % suffix for suffix in suffixes)
    return ("\n".join(lines) + "\n").encode("utf-8")


def compile_canaries(manifest, suffixes):
    """产出消费方换完规则后的自检清单：每行`direct <域名>`或`proxy <域名>`，域名与期望都来自manifest。"""
    lines = set()
    for service_id, service in manifest["services"].items():
        canary = normalize_domain(service["canary"])
        if under_suffix(canary, suffixes):
            raise RuleError("service %s canary %s falls under forced_proxy; pick a domain that stays direct" % (service_id, canary))
        lines.add("direct %s" % canary)
    forced = manifest.get("forced_proxy", {})
    if suffixes:
        canary = normalize_domain(forced["canary"])
        if not under_suffix(canary, suffixes):
            raise RuleError("forced_proxy canary %s is not under any forced suffix" % canary)
        lines.add("proxy %s" % canary)
    for item in manifest.get("canaries", {}).get("proxy", []):
        lines.add("proxy %s" % normalize_domain(item))
    if not any(line.startswith("proxy ") for line in lines):
        raise RuleError("no proxy canary defined; add canaries.proxy to manifest")
    return ("\n".join(sorted(lines)) + "\n").encode("utf-8")


def render_surge_ruleset(services, service_defs):
    """渲染Surge消费的RULE-SET文件：每行DOMAIN-SUFFIX/DOMAIN,<域名>，不带策略。"""
    lines = [
        "# Generated by home-network-rules/update_rules.py. Edit manifest.json, not this file.",
        "# Consume as: RULE-SET,<jsdelivr URL to this file>,DIRECT,update-interval=43200",
    ]
    for service_id, service in service_defs.items():
        lines.append("")
        lines.append("# ===== %s =====" % service["display_name"])
        lines.append("# %s" % service["source_note"])
        for entry in sorted(services[service_id]):
            kind, domain = entry.split(":", 1)
            rule_type = "DOMAIN-SUFFIX" if kind == "domain" else "DOMAIN"
            lines.append("%s,%s" % (rule_type, domain))
    return ("\n".join(lines) + "\n").encode("utf-8")


def atomic_write(path, data, mode=0o644):
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, temp_name = tempfile.mkstemp(prefix=path.name + ".", dir=str(path.parent))
    try:
        with os.fdopen(fd, "wb") as handle:
            handle.write(data)
            handle.flush()
            os.fsync(handle.fileno())
        os.chmod(temp_name, mode)
        os.replace(temp_name, path)
    finally:
        if os.path.exists(temp_name):
            os.unlink(temp_name)


def run(command, input_data=None, timeout=120, check=True, cwd=None):
    result = subprocess.run(
        command,
        input=input_data,
        capture_output=True,
        timeout=timeout,
        cwd=cwd,
    )
    if check and result.returncode != 0:
        raise RuleError(
            "command failed (%s): %s" % (
                " ".join(shlex.quote(str(part)) for part in command),
                result.stderr.decode("utf-8", errors="replace")[-3000:],
            )
        )
    return result


def fetch_source(source_id, source, source_dir=None):
    if source_dir:
        candidates = [source_dir / (source_id + suffix) for suffix in (".txt", ".yaml", ".yml")]
        for candidate in candidates:
            if candidate.exists():
                return candidate.read_text(encoding="utf-8"), str(candidate)
        raise RuleError("fixture source missing: %s" % source_id)

    errors = []
    for url in source["urls"]:
        try:
            request = urllib.request.Request(url, headers={"User-Agent": "home-network-rules/1"})
            with urllib.request.urlopen(request, timeout=30) as response:
                data = response.read(16 * 1024 * 1024 + 1)
                if response.status != 200:
                    raise RuleError("HTTP %s" % response.status)
                if len(data) > 16 * 1024 * 1024:
                    raise RuleError("source exceeds 16 MiB")
                return data.decode("utf-8"), url
        except Exception as exc:
            errors.append("%s: %s" % (url, exc))
    raise RuleError("all source URLs failed for %s: %s" % (source_id, "; ".join(errors)))


def validate_count(source_id, domains, source, previous_counts):
    count = len(domains)
    if count < source["min_count"] or count > source["max_count"]:
        raise RuleError("%s count %d outside [%d, %d]" % (source_id, count, source["min_count"], source["max_count"]))
    previous = previous_counts.get(source_id)
    if previous:
        ratio = abs(count - previous) / previous
        if ratio > 0.20:
            raise RuleError("%s count changed %.1f%% (%d -> %d)" % (source_id, ratio * 100, previous, count))


def compile_rules(manifest, root, source_dir=None):
    state_dir = root / "state"
    baseline_path = state_dir / "baseline-direct-domains.txt"
    additions_path = state_dir / "upstream-additions.txt"
    status_path = state_dir / "status.json"
    baseline = read_rule_entries(baseline_path)
    if len(baseline) < 100000:
        raise RuleError("baseline-direct-domains.txt is missing or too small")
    accumulated = read_rule_entries(additions_path)
    previous_status = json.loads(status_path.read_text(encoding="utf-8")) if status_path.exists() else {}
    previous_counts = previous_status.get("source_counts", {})

    source_counts = {}
    source_urls = {}

    general = manifest["general_direct"]
    text, used_url = fetch_source(general["id"], general, source_dir)
    general_domains = parse_clash_payload(text, general["id"])
    validate_count(general["id"], general_domains, general, previous_counts)
    source_counts[general["id"]] = len(general_domains)
    source_urls[general["id"]] = used_url
    general_exclude = {normalize_domain(item) for item in general.get("exclude", [])}
    eligible_general = without_domains(general_domains, general_exclude)
    newly_seen = eligible_general - baseline - accumulated
    if len(newly_seen) > general["max_new_per_run"]:
        raise RuleError("general direct source introduces %d rules; limit is %d" % (len(newly_seen), general["max_new_per_run"]))
    next_accumulated = without_domains(accumulated | newly_seen, general_exclude)

    suffixes = forced_suffixes(manifest)
    next_accumulated = without_forced(next_accumulated, suffixes)

    services = {}
    service_changes = {}
    for service_id, service in manifest["services"].items():
        text, used_url = fetch_source(service_id, service, source_dir)
        upstream_domains = parse_clash_payload(text, service_id)
        validate_count(service_id, upstream_domains, service, previous_counts)
        source_counts[service_id] = len(upstream_domains)
        source_urls[service_id] = used_url
        include = {"domain:%s" % normalize_domain(item) for item in service.get("include", [])}
        exclude = {normalize_domain(item) for item in service.get("exclude", [])}
        entries = without_forced(without_domains(upstream_domains | include, exclude), suffixes)
        if not entries:
            raise RuleError("service %s compiled to an empty set" % service_id)
        services[service_id] = entries
        prior_path = state_dir / "services" / (service_id + ".txt")
        prior = read_rule_entries(prior_path)
        service_changes[service_id] = {
            "added": sorted(entries - prior),
            "removed": sorted(prior - entries),
        }

    managed = set(next_accumulated)
    for domains in services.values():
        managed.update(domains)

    surge_ruleset_bytes = render_surge_ruleset(services, manifest["services"])
    proxy_entries = {"domain:%s" % suffix for suffix in suffixes}

    return {
        "forced_suffixes": suffixes,
        "proxy_bytes": render_entries(proxy_entries),
        "surge_proxy_bytes": render_surge_proxy_ruleset(suffixes),
        "canaries_bytes": compile_canaries(manifest, suffixes),
        "baseline": baseline,
        "general": general_domains,
        "newly_seen": newly_seen,
        "accumulated": next_accumulated,
        "services": services,
        "managed": managed,
        "managed_bytes": render_entries(managed),
        "surge_ruleset_bytes": surge_ruleset_bytes,
        "source_counts": source_counts,
        "source_urls": source_urls,
        "service_changes": service_changes,
    }


def git_run(root, args, timeout=60, check=True):
    return run(["/usr/bin/git", "-C", str(root)] + args, timeout=timeout, check=check)


def purge_jsdelivr(purge_base_url, repo, branch, path):
    url = "%s/%s@%s/%s" % (purge_base_url.rstrip("/"), repo, branch, path)
    request = urllib.request.Request(url, method="GET")
    try:
        with urllib.request.urlopen(request, timeout=15) as response:
            return {"path": path, "url": url, "status": response.status}
    except Exception as exc:
        return {"path": path, "url": url, "status": None, "error": str(exc)}


def persist_outputs(root, compiled, distribution):
    state_dir = root / "state"
    generated_dir = root / "generated"
    atomic_write(state_dir / "upstream-additions.txt", render_entries(compiled["accumulated"]), 0o600)
    for service_id, entries in compiled["services"].items():
        atomic_write(state_dir / "services" / (service_id + ".txt"), render_entries(entries), 0o600)
    atomic_write(root / distribution["managed_rules_path"], compiled["managed_bytes"], 0o644)
    atomic_write(root / distribution["surge_ruleset_path"], compiled["surge_ruleset_bytes"], 0o644)
    atomic_write(root / distribution["managed_proxy_rules_path"], compiled["proxy_bytes"], 0o644)
    atomic_write(root / distribution["surge_proxy_ruleset_path"], compiled["surge_proxy_bytes"], 0o644)
    atomic_write(root / distribution["canaries_path"], compiled["canaries_bytes"], 0o644)


PUBLISHED_PATH_KEYS = ("managed_rules_path", "surge_ruleset_path", "managed_proxy_rules_path", "surge_proxy_ruleset_path", "canaries_path")


def commit_and_publish(root, distribution):
    """git add -A后若暂存区非空则提交推送并请求jsdelivr刷新；无变化返回None。"""
    git_run(root, ["add", "-A"])
    diff = git_run(root, ["diff", "--cached", "--quiet"], check=False)
    if diff.returncode == 0:
        return None

    head_before = git_run(root, ["rev-parse", "HEAD"], check=False)
    previous_head = head_before.stdout.decode().strip() if head_before.returncode == 0 else None

    commit_message = "Update generated rules (%s)" % utc_now()
    git_run(root, ["commit", "-m", commit_message])
    try:
        git_run(root, ["push", "origin", distribution["branch"]], timeout=120)
    except Exception:
        if previous_head:
            git_run(root, ["reset", "--hard", previous_head], check=False)
        raise

    purge_results = [
        purge_jsdelivr(distribution["purge_base_url"], distribution["repo"], distribution["branch"], distribution[key])
        for key in PUBLISHED_PATH_KEYS
    ]
    new_head = git_run(root, ["rev-parse", "HEAD"]).stdout.decode().strip()
    return {"commit": new_head, "message": commit_message, "purge": purge_results}


def write_status(root, compiled, publish_result):
    state_dir = root / "state"
    change = {
        "at": utc_now(),
        "new_general_domains": sorted(compiled["newly_seen"]),
        "service_changes": compiled["service_changes"],
        "publish": publish_result,
    }
    atomic_write(state_dir / "last-change.json", (json.dumps(change, ensure_ascii=False, indent=2) + "\n").encode("utf-8"), 0o600)
    status = {
        "last_success": utc_now(),
        "baseline_count": len(compiled["baseline"]),
        "source_counts": compiled["source_counts"],
        "source_urls": compiled["source_urls"],
        "accumulated_upstream_additions": len(compiled["accumulated"]),
        "managed_domain_count": len(compiled["managed"]),
        "managed_sha256": sha256_bytes(compiled["managed_bytes"]),
        "surge_ruleset_sha256": sha256_bytes(compiled["surge_ruleset_bytes"]),
        "forced_proxy_suffixes": compiled["forced_suffixes"],
        "managed_proxy_sha256": sha256_bytes(compiled["proxy_bytes"]),
        "surge_proxy_ruleset_sha256": sha256_bytes(compiled["surge_proxy_bytes"]),
        "canaries_sha256": sha256_bytes(compiled["canaries_bytes"]),
        "publish": publish_result,
    }
    atomic_write(state_dir / "status.json", (json.dumps(status, ensure_ascii=False, indent=2) + "\n").encode("utf-8"), 0o600)
    failure_path = state_dir / "last-failure.json"
    if failure_path.exists():
        failure_path.unlink()


def write_failure(root, exc):
    payload = {"at": utc_now(), "error": str(exc)}
    atomic_write(root / "state" / "last-failure.json", (json.dumps(payload, ensure_ascii=False, indent=2) + "\n").encode("utf-8"), 0o600)


def setup_logging(root, log_file=None):
    log_path = log_file or (Path.home() / "Library" / "Logs" / "home-network-rules.log")
    log_path.parent.mkdir(parents=True, exist_ok=True)
    handler = RotatingFileHandler(log_path, maxBytes=5 * 1024 * 1024, backupCount=3, encoding="utf-8")
    handler.setFormatter(logging.Formatter("%(asctime)s %(levelname)s %(message)s"))
    logger = logging.getLogger("home-network-rules")
    logger.setLevel(logging.INFO)
    logger.addHandler(handler)
    return logger


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--apply", action="store_true", help="write generated files and publish to GitHub when changed")
    parser.add_argument("--source-dir", type=Path, help="read fixture sources instead of the network")
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parent)
    parser.add_argument("--log-file", type=Path)
    args = parser.parse_args()
    root = args.root.resolve()
    logger = setup_logging(root, args.log_file)
    manifest = json.loads((root / "manifest.json").read_text(encoding="utf-8"))
    if manifest.get("schema_version") != 2:
        raise SystemExit("unsupported manifest schema")
    try:
        compiled = compile_rules(manifest, root, args.source_dir)
        summary = {
            "baseline": len(compiled["baseline"]),
            "general_source": len(compiled["general"]),
            "new_general": len(compiled["newly_seen"]),
            "accumulated": len(compiled["accumulated"]),
            "services": {name: len(domains) for name, domains in compiled["services"].items()},
            "managed": len(compiled["managed"]),
            "managed_sha256": sha256_bytes(compiled["managed_bytes"]),
            "surge_ruleset_sha256": sha256_bytes(compiled["surge_ruleset_bytes"]),
            "forced_proxy": compiled["forced_suffixes"],
            "canaries": compiled["canaries_bytes"].decode("utf-8").split("\n")[:-1],
        }
        if not args.apply:
            print(json.dumps(summary, ensure_ascii=False, indent=2))
            return 0

        distribution = manifest["distribution"]
        persist_outputs(root, compiled, distribution)
        publish_result = commit_and_publish(root, distribution)
        write_status(root, compiled, publish_result)
        logger.info("update succeeded: %s", json.dumps({**summary, "publish": publish_result}, ensure_ascii=False, sort_keys=True))
        print(json.dumps({**summary, "publish": publish_result}, ensure_ascii=False, indent=2))
        return 0
    except Exception as exc:
        write_failure(root, exc)
        logger.exception("update failed")
        print("home-network-rules: %s" % exc, file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
